[auth]
redirect_uri = "https://whiteloverapp.streamlit.app/oauth2callback"
cookie_secret = "ccb12720d273e4173e5a14f1276e744690852a0f0697c3eb7f935a744b4590d1"
client_id = "240909589080-5ej9t6rc76m9ula67ptvfdg2blou1t66.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
